// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG1Hec94JersgH3Wn7vns7cvcDs5EhIn4',
    appId: '1:834087782573:web:fa59d34eedb9c17f219e24',
    messagingSenderId: '834087782573',
    projectId: 'taskapp-dcca3',
    authDomain: 'taskapp-dcca3.firebaseapp.com',
    storageBucket: 'taskapp-dcca3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4vr7XtRmMWdOvVro1F2e6uXRfRU_92lc',
    appId: '1:834087782573:android:c22a23947b1321db219e24',
    messagingSenderId: '834087782573',
    projectId: 'taskapp-dcca3',
    storageBucket: 'taskapp-dcca3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALE33dUJt1moerfxyWtn8QsgE9dkN4yVU',
    appId: '1:834087782573:ios:13e0c86fbab9ad99219e24',
    messagingSenderId: '834087782573',
    projectId: 'taskapp-dcca3',
    storageBucket: 'taskapp-dcca3.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALE33dUJt1moerfxyWtn8QsgE9dkN4yVU',
    appId: '1:834087782573:ios:b4b4cb92999b87e2219e24',
    messagingSenderId: '834087782573',
    projectId: 'taskapp-dcca3',
    storageBucket: 'taskapp-dcca3.appspot.com',
    iosBundleId: 'com.example.todolistApp.RunnerTests',
  );
}
